
import json

# Your JSON data (replace this with your actual JSON data)
json_data = '''[
    {
        "submission_date": "5/11/2021",
        "new_case": "561",
        "new_death": "31",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44327"
    },
    {
        "submission_date": "7/3/2021",
        "new_case": "190",
        "new_death": "5",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44380"
    },
    {
        "submission_date": "10/8/2021",
        "new_case": "1869",
        "new_death": "19",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44477"
    },
    {
        "submission_date": "3/18/2021",
        "new_case": "4473",
        "new_death": "31",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44273"
    },
    {
        "submission_date": "6/26/2021",
        "new_case": "237",
        "new_death": "6",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44373"
    },
    {
        "submission_date": "12/15/2021",
        "new_case": "4989",
        "new_death": "30",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44545"
    },
    {
        "submission_date": "3/2/2021",
        "new_case": "3289",
        "new_death": "48",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44257"
    },
    {
        "submission_date": "12/13/2021",
        "new_case": "3279",
        "new_death": "13",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44543"
    },
    {
        "submission_date": "4/21/2021",
        "new_case": "3475",
        "new_death": "65",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44307"
    },
    {
        "submission_date": "7/8/2021",
        "new_case": "331",
        "new_death": "3",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44385"
    },
    {
        "submission_date": "1/16/2021",
        "new_case": "6057",
        "new_death": "94",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44212"
    },
    {
        "submission_date": "3/10/2021",
        "new_case": "3775",
        "new_death": "133",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44265"
    },
    {
        "submission_date": "7/24/2021",
        "new_case": "861",
        "new_death": "5",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44401"
    },
    {
        "submission_date": "1/6/2021",
        "new_case": "5848",
        "new_death": "141",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44202"
    },
    {
        "submission_date": "9/29/2021",
        "new_case": "1997",
        "new_death": "20",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44468"
    },
    {
        "submission_date": "8/18/2021",
        "new_case": "1677",
        "new_death": "6",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44426"
    },
    {
        "submission_date": "3/13/2021",
        "new_case": "4034",
        "new_death": "34",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44268"
    },
    {
        "submission_date": "12/24/2021",
        "new_case": "18941",
        "new_death": "26",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44554"
    },
    {
        "submission_date": "12/18/2021",
        "new_case": "7644",
        "new_death": "33",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44548"
    },
    {
        "submission_date": "6/4/2021",
        "new_case": "288",
        "new_death": "18",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44351"
    },
    {
        "submission_date": "3/12/2021",
        "new_case": "4049",
        "new_death": "40",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44267"
    },
    {
        "submission_date": "12/23/2021",
        "new_case": "18122",
        "new_death": "32",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44553"
    },
    {
        "submission_date": "10/4/2021",
        "new_case": "1246",
        "new_death": "16",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44473"
    },
    {
        "submission_date": "3/5/2021",
        "new_case": "3701",
        "new_death": "30",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44260"
    },
    {
        "submission_date": "9/3/2021",
        "new_case": "1735",
        "new_death": "10",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44442"
    },
    {
        "submission_date": "10/1/2021",
        "new_case": "1673",
        "new_death": "16",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44470"
    },
    {
        "submission_date": "10/9/2021",
        "new_case": "1828",
        "new_death": "20",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44478"
    },
    {
        "submission_date": "5/6/2021",
        "new_case": "1413",
        "new_death": "33",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44322"
    },
    {
        "submission_date": "11/13/2021",
        "new_case": "1638",
        "new_death": "17",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44513"
    },
    {
        "submission_date": "8/24/2021",
        "new_case": "1857",
        "new_death": "20",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44432"
    },
    {
        "submission_date": "6/1/2021",
        "new_case": "158",
        "new_death": "7",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44348"
    },
    {
        "submission_date": "7/11/2021",
        "new_case": "283",
        "new_death": "4",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44388"
    },
    {
        "submission_date": "3/17/2021",
        "new_case": "4313",
        "new_death": "79",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44272"
    },
    {
        "submission_date": "7/5/2021",
        "new_case": "86",
        "new_death": "4",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44382"
    },
    {
        "submission_date": "7/19/2021",
        "new_case": "312",
        "new_death": "6",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44396"
    },
    {
        "submission_date": "5/16/2021",
        "new_case": "269",
        "new_death": "9",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44332"
    },
    {
        "submission_date": "7/14/2021",
        "new_case": "365",
        "new_death": "11",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44391"
    },
    {
        "submission_date": "2/28/2021",
        "new_case": "2389",
        "new_death": "14",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44255"
    },
    {
        "submission_date": "11/11/2021",
        "new_case": "1823",
        "new_death": "12",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44511"
    },
    {
        "submission_date": "4/5/2021",
        "new_case": "2831",
        "new_death": "12",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44291"
    },
    {
        "submission_date": "12/9/2021",
        "new_case": "5617",
        "new_death": "8",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44539"
    },
    {
        "submission_date": "1/11/2021",
        "new_case": "5334",
        "new_death": "46",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44207"
    },
    {
        "submission_date": "11/10/2021",
        "new_case": "1338",
        "new_death": "15",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44510"
    },
    {
        "submission_date": "10/12/2021",
        "new_case": "1642",
        "new_death": "21",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44481"
    },
    {
        "submission_date": "5/10/2021",
        "new_case": "152",
        "new_death": "9",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44326"
    },
    {
        "submission_date": "11/6/2021",
        "new_case": "1403",
        "new_death": "18",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44506"
    },
    {
        "submission_date": "3/21/2021",
        "new_case": "3238",
        "new_death": "40",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44276"
    },
    {
        "submission_date": "4/13/2021",
        "new_case": "4848",
        "new_death": "49",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44299"
    },
    {
        "submission_date": "10/24/2021",
        "new_case": "787",
        "new_death": "3",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44493"
    },
    {
        "submission_date": "9/26/2021",
        "new_case": "1110",
        "new_death": "5",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44465"
    },
    {
        "submission_date": "8/21/2021",
        "new_case": "2158",
        "new_death": "11",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44429"
    },
    {
        "submission_date": "12/8/2021",
        "new_case": "4258",
        "new_death": "24",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44538"
    },
    {
        "submission_date": "6/9/2021",
        "new_case": "184",
        "new_death": "22",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44356"
    },
    {
        "submission_date": "6/10/2021",
        "new_case": "342",
        "new_death": "6",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44357"
    },
    {
        "submission_date": "10/15/2021",
        "new_case": "1383",
        "new_death": "19",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44484"
    },
    {
        "submission_date": "8/8/2021",
        "new_case": "1169",
        "new_death": "5",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44416"
    },
    {
        "submission_date": "6/3/2021",
        "new_case": "286",
        "new_death": "0",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44350"
    },
    {
        "submission_date": "12/12/2021",
        "new_case": "3842",
        "new_death": "8",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44542"
    },
    {
        "submission_date": "1/10/2021",
        "new_case": "5646",
        "new_death": "32",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44206"
    },
    {
        "submission_date": "3/27/2021",
        "new_case": "4662",
        "new_death": "24",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44282"
    },
    {
        "submission_date": "2/14/2021",
        "new_case": "2168",
        "new_death": "14",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44241"
    },
    {
        "submission_date": "11/26/2021",
        "new_case": "2144",
        "new_death": "3",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44526"
    },
    {
        "submission_date": "10/20/2021",
        "new_case": "1106",
        "new_death": "15",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44489"
    },
    {
        "submission_date": "12/3/2021",
        "new_case": "4463",
        "new_death": "14",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44533"
    },
    {
        "submission_date": "3/1/2021",
        "new_case": "3140",
        "new_death": "21",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44256"
    },
    {
        "submission_date": "10/27/2021",
        "new_case": "1289",
        "new_death": "33",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44496"
    },
    {
        "submission_date": "5/19/2021",
        "new_case": "444",
        "new_death": "32",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44335"
    },
    {
        "submission_date": "2/24/2021",
        "new_case": "3119",
        "new_death": "99",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44251"
    },
    {
        "submission_date": "12/16/2021",
        "new_case": "7223",
        "new_death": "16",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44546"
    },
    {
        "submission_date": "7/22/2021",
        "new_case": "746",
        "new_death": "2",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44399"
    },
    {
        "submission_date": "12/6/2021",
        "new_case": "2989",
        "new_death": "8",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44536"
    },
    {
        "submission_date": "7/13/2021",
        "new_case": "363",
        "new_death": "7",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44390"
    },
    {
        "submission_date": "1/14/2021",
        "new_case": "7092",
        "new_death": "92",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44210"
    },
    {
        "submission_date": "8/29/2021",
        "new_case": "1850",
        "new_death": "5",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44437"
    },
    {
        "submission_date": "1/27/2021",
        "new_case": "4810",
        "new_death": "115",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44223"
    },
    {
        "submission_date": "4/24/2021",
        "new_case": "2783",
        "new_death": "39",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44310"
    },
    {
        "submission_date": "10/11/2021",
        "new_case": "954",
        "new_death": "6",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44480"
    },
    {
        "submission_date": "4/28/2021",
        "new_case": "2113",
        "new_death": "49",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44314"
    },
    {
        "submission_date": "7/18/2021",
        "new_case": "428",
        "new_death": "3",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44395"
    },
    {
        "submission_date": "11/2/2021",
        "new_case": "1215",
        "new_death": "24",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44502"
    },
    {
        "submission_date": "2/27/2021",
        "new_case": "4134",
        "new_death": "46",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44254"
    },
    {
        "submission_date": "5/8/2021",
        "new_case": "650",
        "new_death": "22",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44324"
    },
    {
        "submission_date": "9/25/2021",
        "new_case": "2234",
        "new_death": "16",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44464"
    },
    {
        "submission_date": "4/6/2021",
        "new_case": "3710",
        "new_death": "51",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44292"
    },
    {
        "submission_date": "2/17/2021",
        "new_case": "4109",
        "new_death": "135",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44244"
    },
    {
        "submission_date": "8/30/2021",
        "new_case": "1508",
        "new_death": "15",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44438"
    },
    {
        "submission_date": "1/28/2021",
        "new_case": "4746",
        "new_death": "81",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44224"
    },
    {
        "submission_date": "10/3/2021",
        "new_case": "1454",
        "new_death": "7",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44472"
    },
    {
        "submission_date": "12/30/2021",
        "new_case": "35175",
        "new_death": "33",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44560"
    },
    {
        "submission_date": "6/18/2021",
        "new_case": "205",
        "new_death": "3",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44365"
    },
    {
        "submission_date": "5/14/2021",
        "new_case": "323",
        "new_death": "26",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44330"
    },
    {
        "submission_date": "11/15/2021",
        "new_case": "1362",
        "new_death": "5",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44515"
    },
    {
        "submission_date": "4/25/2021",
        "new_case": "1694",
        "new_death": "13",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44311"
    },
    {
        "submission_date": "10/5/2021",
        "new_case": "1648",
        "new_death": "37",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44474"
    },
    {
        "submission_date": "9/20/2021",
        "new_case": "1623",
        "new_death": "12",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44459"
    },
    {
        "submission_date": "7/16/2021",
        "new_case": "494",
        "new_death": "2",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44393"
    },
    {
        "submission_date": "9/21/2021",
        "new_case": "2165",
        "new_death": "38",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44460"
    },
    {
        "submission_date": "7/12/2021",
        "new_case": "215",
        "new_death": "4",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44389"
    },
    {
        "submission_date": "11/27/2021",
        "new_case": "1990",
        "new_death": "9",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44527"
    },
    {
        "submission_date": "8/25/2021",
        "new_case": "2113",
        "new_death": "21",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44433"
    },
    {
        "submission_date": "2/21/2021",
        "new_case": "2031",
        "new_death": "24",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44248"
    },
    {
        "submission_date": "2/1/2021",
        "new_case": "3517",
        "new_death": "29",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44228"
    },
    {
        "submission_date": "4/2/2021",
        "new_case": "4529",
        "new_death": "24",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44288"
    },
    {
        "submission_date": "12/10/2021",
        "new_case": "5463",
        "new_death": "17",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44540"
    },
    {
        "submission_date": "10/22/2021",
        "new_case": "1706",
        "new_death": "23",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44491"
    },
    {
        "submission_date": "6/2/2021",
        "new_case": "273",
        "new_death": "28",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44349"
    },
    {
        "submission_date": "4/12/2021",
        "new_case": "1583",
        "new_death": "26",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44298"
    },
    {
        "submission_date": "1/30/2021",
        "new_case": "5274",
        "new_death": "108",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44226"
    },
    {
        "submission_date": "5/18/2021",
        "new_case": "646",
        "new_death": "23",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44334"
    },
    {
        "submission_date": "7/27/2021",
        "new_case": "794",
        "new_death": "7",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44404"
    },
    {
        "submission_date": "11/28/2021",
        "new_case": "1869",
        "new_death": "4",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44528"
    },
    {
        "submission_date": "7/25/2021",
        "new_case": "596",
        "new_death": "2",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44402"
    },
    {
        "submission_date": "2/6/2021",
        "new_case": "4511",
        "new_death": "78",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44233"
    },
    {
        "submission_date": "4/9/2021",
        "new_case": "4193",
        "new_death": "43",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44295"
    },
    {
        "submission_date": "12/1/2021",
        "new_case": "3188",
        "new_death": "19",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44531"
    },
    {
        "submission_date": "8/11/2021",
        "new_case": "1686",
        "new_death": "6",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44419"
    },
    {
        "submission_date": "8/14/2021",
        "new_case": "2564",
        "new_death": "11",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44422"
    },
    {
        "submission_date": "2/25/2021",
        "new_case": "3577",
        "new_death": "70",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44252"
    },
    {
        "submission_date": "8/12/2021",
        "new_case": "1854",
        "new_death": "7",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44420"
    },
    {
        "submission_date": "5/13/2021",
        "new_case": "428",
        "new_death": "24",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44329"
    },
    {
        "submission_date": "11/22/2021",
        "new_case": "1543",
        "new_death": "11",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44522"
    },
    {
        "submission_date": "6/12/2021",
        "new_case": "249",
        "new_death": "3",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44359"
    },
    {
        "submission_date": "5/28/2021",
        "new_case": "266",
        "new_death": "12",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44344"
    },
    {
        "submission_date": "2/7/2021",
        "new_case": "4332",
        "new_death": "25",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44234"
    },
    {
        "submission_date": "3/9/2021",
        "new_case": "4126",
        "new_death": "45",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44264"
    },
    {
        "submission_date": "8/22/2021",
        "new_case": "1450",
        "new_death": "2",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44430"
    },
    {
        "submission_date": "3/16/2021",
        "new_case": "3878",
        "new_death": "41",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44271"
    },
    {
        "submission_date": "7/6/2021",
        "new_case": "154",
        "new_death": "0",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44383"
    },
    {
        "submission_date": "6/22/2021",
        "new_case": "246",
        "new_death": "15",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44369"
    },
    {
        "submission_date": "8/15/2021",
        "new_case": "1274",
        "new_death": "3",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44423"
    },
    {
        "submission_date": "1/12/2021",
        "new_case": "4587",
        "new_death": "107",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44208"
    },
    {
        "submission_date": "4/15/2021",
        "new_case": "3917",
        "new_death": "47",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44301"
    },
    {
        "submission_date": "11/3/2021",
        "new_case": "1298",
        "new_death": "7",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44503"
    },
    {
        "submission_date": "12/17/2021",
        "new_case": "7397",
        "new_death": "16",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44547"
    },
    {
        "submission_date": "10/21/2021",
        "new_case": "1468",
        "new_death": "22",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44490"
    },
    {
        "submission_date": "1/19/2021",
        "new_case": "4628",
        "new_death": "54",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44215"
    },
    {
        "submission_date": "10/26/2021",
        "new_case": "1473",
        "new_death": "33",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44495"
    },
    {
        "submission_date": "10/10/2021",
        "new_case": "1433",
        "new_death": "7",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44479"
    },
    {
        "submission_date": "10/6/2021",
        "new_case": "1852",
        "new_death": "17",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44475"
    },
    {
        "submission_date": "9/5/2021",
        "new_case": "1714",
        "new_death": "6",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44444"
    },
    {
        "submission_date": "5/26/2021",
        "new_case": "395",
        "new_death": "35",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44342"
    },
    {
        "submission_date": "5/29/2021",
        "new_case": "255",
        "new_death": "16",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44345"
    },
    {
        "submission_date": "9/11/2021",
        "new_case": "2494",
        "new_death": "15",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44450"
    },
    {
        "submission_date": "1/25/2021",
        "new_case": "4143",
        "new_death": "21",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44221"
    },
    {
        "submission_date": "6/21/2021",
        "new_case": "126",
        "new_death": "3",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44368"
    },
    {
        "submission_date": "5/2/2021",
        "new_case": "1198",
        "new_death": "12",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44318"
    },
    {
        "submission_date": "9/8/2021",
        "new_case": "3498",
        "new_death": "29",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44447"
    },
    {
        "submission_date": "5/20/2021",
        "new_case": "561",
        "new_death": "23",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44336"
    },
    {
        "submission_date": "8/20/2021",
        "new_case": "2940",
        "new_death": "8",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44428"
    },
    {
        "submission_date": "5/1/2021",
        "new_case": "1589",
        "new_death": "34",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44317"
    },
    {
        "submission_date": "8/16/2021",
        "new_case": "1304",
        "new_death": "1",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44424"
    },
    {
        "submission_date": "7/30/2021",
        "new_case": "1119",
        "new_death": "5",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44407"
    },
    {
        "submission_date": "3/3/2021",
        "new_case": "3691",
        "new_death": "128",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44258"
    },
    {
        "submission_date": "9/14/2021",
        "new_case": "2038",
        "new_death": "22",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44453"
    },
    {
        "submission_date": "3/14/2021",
        "new_case": "3310",
        "new_death": "15",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44269"
    },
    {
        "submission_date": "8/26/2021",
        "new_case": "2054",
        "new_death": "11",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44434"
    },
    {
        "submission_date": "4/29/2021",
        "new_case": "2359",
        "new_death": "20",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44315"
    },
    {
        "submission_date": "2/12/2021",
        "new_case": "3732",
        "new_death": "64",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44239"
    },
    {
        "submission_date": "9/6/2021",
        "new_case": "1951",
        "new_death": "4",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44445"
    },
    {
        "submission_date": "11/24/2021",
        "new_case": "2208",
        "new_death": "12",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44524"
    },
    {
        "submission_date": "11/21/2021",
        "new_case": "1602",
        "new_death": "4",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44521"
    },
    {
        "submission_date": "3/28/2021",
        "new_case": "4509",
        "new_death": "7",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44283"
    },
    {
        "submission_date": "2/9/2021",
        "new_case": "3576",
        "new_death": "92",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44236"
    },
    {
        "submission_date": "12/11/2021",
        "new_case": "4596",
        "new_death": "25",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44541"
    },
    {
        "submission_date": "3/25/2021",
        "new_case": "3946",
        "new_death": "38",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44280"
    },
    {
        "submission_date": "12/7/2021",
        "new_case": "3950",
        "new_death": "29",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44537"
    },
    {
        "submission_date": "3/29/2021",
        "new_case": "3621",
        "new_death": "15",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44284"
    },
    {
        "submission_date": "7/20/2021",
        "new_case": "658",
        "new_death": "12",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44397"
    },
    {
        "submission_date": "3/30/2021",
        "new_case": "4871",
        "new_death": "82",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44285"
    },
    {
        "submission_date": "6/6/2021",
        "new_case": "209",
        "new_death": "6",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44353"
    },
    {
        "submission_date": "2/26/2021",
        "new_case": "3870",
        "new_death": "45",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44253"
    },
    {
        "submission_date": "1/23/2021",
        "new_case": "7147",
        "new_death": "59",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44219"
    },
    {
        "submission_date": "2/4/2021",
        "new_case": "3289",
        "new_death": "100",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44231"
    },
    {
        "submission_date": "11/12/2021",
        "new_case": "1821",
        "new_death": "6",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44512"
    },
    {
        "submission_date": "6/15/2021",
        "new_case": "249",
        "new_death": "11",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44362"
    },
    {
        "submission_date": "4/11/2021",
        "new_case": "3387",
        "new_death": "11",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44297"
    },
    {
        "submission_date": "9/1/2021",
        "new_case": "2283",
        "new_death": "20",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44440"
    },
    {
        "submission_date": "7/7/2021",
        "new_case": "283",
        "new_death": "13",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44384"
    },
    {
        "submission_date": "2/8/2021",
        "new_case": "2561",
        "new_death": "22",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44235"
    },
    {
        "submission_date": "5/7/2021",
        "new_case": "967",
        "new_death": "29",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44323"
    },
    {
        "submission_date": "1/24/2021",
        "new_case": "5272",
        "new_death": "17",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44220"
    },
    {
        "submission_date": "7/1/2021",
        "new_case": "218",
        "new_death": "5",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44378"
    },
    {
        "submission_date": "6/17/2021",
        "new_case": "238",
        "new_death": "7",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44364"
    },
    {
        "submission_date": "11/1/2021",
        "new_case": "821",
        "new_death": "8",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44501"
    },
    {
        "submission_date": "5/30/2021",
        "new_case": "246",
        "new_death": "6",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44346"
    },
    {
        "submission_date": "6/30/2021",
        "new_case": "195",
        "new_death": "13",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44377"
    },
    {
        "submission_date": "11/4/2021",
        "new_case": "1504",
        "new_death": "0",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44504"
    },
    {
        "submission_date": "12/19/2021",
        "new_case": "7345",
        "new_death": "6",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44549"
    },
    {
        "submission_date": "10/16/2021",
        "new_case": "1452",
        "new_death": "28",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44485"
    },
    {
        "submission_date": "4/18/2021",
        "new_case": "3149",
        "new_death": "9",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44304"
    },
    {
        "submission_date": "3/23/2021",
        "new_case": "4803",
        "new_death": "61",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44278"
    },
    {
        "submission_date": "1/17/2021",
        "new_case": "5132",
        "new_death": "25",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44213"
    },
    {
        "submission_date": "12/2/2021",
        "new_case": "4462",
        "new_death": "11",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44532"
    },
    {
        "submission_date": "6/23/2021",
        "new_case": "268",
        "new_death": "18",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44370"
    },
    {
        "submission_date": "3/8/2021",
        "new_case": "2307",
        "new_death": "16",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44263"
    },
    {
        "submission_date": "1/22/2021",
        "new_case": "4200",
        "new_death": "115",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44218"
    },
    {
        "submission_date": "9/2/2021",
        "new_case": "2542",
        "new_death": "17",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44441"
    },
    {
        "submission_date": "3/19/2021",
        "new_case": "4390",
        "new_death": "27",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44274"
    },
    {
        "submission_date": "4/3/2021",
        "new_case": "4445",
        "new_death": "17",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44289"
    },
    {
        "submission_date": "4/1/2021",
        "new_case": "5606",
        "new_death": "30",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44287"
    },
    {
        "submission_date": "11/18/2021",
        "new_case": "2473",
        "new_death": "10",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44518"
    },
    {
        "submission_date": "8/3/2021",
        "new_case": "1313",
        "new_death": "8",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44411"
    },
    {
        "submission_date": "12/22/2021",
        "new_case": "11906",
        "new_death": "28",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44552"
    },
    {
        "submission_date": "2/10/2021",
        "new_case": "4370",
        "new_death": "147",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44237"
    },
    {
        "submission_date": "2/2/2021",
        "new_case": "3150",
        "new_death": "71",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44229"
    },
    {
        "submission_date": "9/22/2021",
        "new_case": "2351",
        "new_death": "24",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44461"
    },
    {
        "submission_date": "6/19/2021",
        "new_case": "205",
        "new_death": "3",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44366"
    },
    {
        "submission_date": "8/28/2021",
        "new_case": "1934",
        "new_death": "18",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44436"
    },
    {
        "submission_date": "6/5/2021",
        "new_case": "358",
        "new_death": "8",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44352"
    },
    {
        "submission_date": "4/19/2021",
        "new_case": "2183",
        "new_death": "18",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44305"
    },
    {
        "submission_date": "5/23/2021",
        "new_case": "301",
        "new_death": "7",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44339"
    },
    {
        "submission_date": "4/20/2021",
        "new_case": "2839",
        "new_death": "45",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44306"
    },
    {
        "submission_date": "12/27/2021",
        "new_case": "9732",
        "new_death": "8",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44557"
    },
    {
        "submission_date": "7/23/2021",
        "new_case": "909",
        "new_death": "4",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44400"
    },
    {
        "submission_date": "7/15/2021",
        "new_case": "446",
        "new_death": "2",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44392"
    },
    {
        "submission_date": "6/11/2021",
        "new_case": "274",
        "new_death": "2",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44358"
    },
    {
        "submission_date": "9/30/2021",
        "new_case": "2327",
        "new_death": "27",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44469"
    },
    {
        "submission_date": "3/20/2021",
        "new_case": "4909",
        "new_death": "31",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44275"
    },
    {
        "submission_date": "6/8/2021",
        "new_case": "195",
        "new_death": "9",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44355"
    },
    {
        "submission_date": "4/26/2021",
        "new_case": "0",
        "new_death": "19",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44312"
    },
    {
        "submission_date": "1/2/2021",
        "new_case": "5959",
        "new_death": "27",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44198"
    },
    {
        "submission_date": "5/12/2021",
        "new_case": "486",
        "new_death": "41",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44328"
    },
    {
        "submission_date": "1/1/2021",
        "new_case": "5803",
        "new_death": "118",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44197"
    },
    {
        "submission_date": "8/7/2021",
        "new_case": "1539",
        "new_death": "9",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44415"
    },
    {
        "submission_date": "2/20/2021",
        "new_case": "2876",
        "new_death": "50",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44247"
    },
    {
        "submission_date": "9/18/2021",
        "new_case": "2623",
        "new_death": "17",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44457"
    },
    {
        "submission_date": "1/29/2021",
        "new_case": "5986",
        "new_death": "82",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44225"
    },
    {
        "submission_date": "3/11/2021",
        "new_case": "3815",
        "new_death": "46",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44266"
    },
    {
        "submission_date": "9/4/2021",
        "new_case": "2248",
        "new_death": "13",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44443"
    },
    {
        "submission_date": "12/28/2021",
        "new_case": "15234",
        "new_death": "48",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44558"
    },
    {
        "submission_date": "9/9/2021",
        "new_case": "2210",
        "new_death": "17",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44448"
    },
    {
        "submission_date": "10/23/2021",
        "new_case": "1140",
        "new_death": "20",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44492"
    },
    {
        "submission_date": "4/8/2021",
        "new_case": "4332",
        "new_death": "34",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44294"
    },
    {
        "submission_date": "9/13/2021",
        "new_case": "1545",
        "new_death": "21",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44452"
    },
    {
        "submission_date": "7/28/2021",
        "new_case": "948",
        "new_death": "3",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44405"
    },
    {
        "submission_date": "1/5/2021",
        "new_case": "5328",
        "new_death": "138",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44201"
    },
    {
        "submission_date": "7/9/2021",
        "new_case": "398",
        "new_death": "3",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44386"
    },
    {
        "submission_date": "2/23/2021",
        "new_case": "3158",
        "new_death": "104",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44250"
    },
    {
        "submission_date": "11/17/2021",
        "new_case": "1948",
        "new_death": "20",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44517"
    },
    {
        "submission_date": "5/21/2021",
        "new_case": "652",
        "new_death": "17",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44337"
    },
    {
        "submission_date": "8/5/2021",
        "new_case": "1466",
        "new_death": "4",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44413"
    },
    {
        "submission_date": "7/17/2021",
        "new_case": "549",
        "new_death": "5",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44394"
    },
    {
        "submission_date": "4/14/2021",
        "new_case": "3563",
        "new_death": "61",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44300"
    },
    {
        "submission_date": "4/16/2021",
        "new_case": "4381",
        "new_death": "41",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44302"
    },
    {
        "submission_date": "5/27/2021",
        "new_case": "394",
        "new_death": "14",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44343"
    },
    {
        "submission_date": "11/16/2021",
        "new_case": "1739",
        "new_death": "23",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44516"
    },
    {
        "submission_date": "10/17/2021",
        "new_case": "896",
        "new_death": "5",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44486"
    },
    {
        "submission_date": "9/10/2021",
        "new_case": "2664",
        "new_death": "15",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44449"
    },
    {
        "submission_date": "12/29/2021",
        "new_case": "26473",
        "new_death": "50",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44559"
    },
    {
        "submission_date": "8/4/2021",
        "new_case": "1230",
        "new_death": "11",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44412"
    },
    {
        "submission_date": "1/26/2021",
        "new_case": "4776",
        "new_death": "133",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44222"
    },
    {
        "submission_date": "3/7/2021",
        "new_case": "2519",
        "new_death": "17",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44262"
    },
    {
        "submission_date": "4/17/2021",
        "new_case": "3922",
        "new_death": "40",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44303"
    },
    {
        "submission_date": "5/22/2021",
        "new_case": "378",
        "new_death": "14",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44338"
    },
    {
        "submission_date": "9/17/2021",
        "new_case": "2374",
        "new_death": "17",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44456"
    },
    {
        "submission_date": "12/25/2021",
        "new_case": "19481",
        "new_death": "6",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44555"
    },
    {
        "submission_date": "3/31/2021",
        "new_case": "3672",
        "new_death": "75",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44286"
    },
    {
        "submission_date": "9/15/2021",
        "new_case": "2275",
        "new_death": "21",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44454"
    },
    {
        "submission_date": "2/15/2021",
        "new_case": "1445",
        "new_death": "12",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44242"
    },
    {
        "submission_date": "5/17/2021",
        "new_case": "347",
        "new_death": "14",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44333"
    },
    {
        "submission_date": "10/14/2021",
        "new_case": "1638",
        "new_death": "20",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44483"
    },
    {
        "submission_date": "3/22/2021",
        "new_case": "3151",
        "new_death": "7",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44277"
    },
    {
        "submission_date": "6/25/2021",
        "new_case": "349",
        "new_death": "12",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44372"
    },
    {
        "submission_date": "5/24/2021",
        "new_case": "102",
        "new_death": "9",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44340"
    },
    {
        "submission_date": "1/13/2021",
        "new_case": "7880",
        "new_death": "122",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44209"
    },
    {
        "submission_date": "3/24/2021",
        "new_case": "4096",
        "new_death": "50",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44279"
    },
    {
        "submission_date": "1/4/2021",
        "new_case": "2496",
        "new_death": "36",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44200"
    },
    {
        "submission_date": "7/4/2021",
        "new_case": "112",
        "new_death": "1",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44381"
    },
    {
        "submission_date": "1/8/2021",
        "new_case": "5769",
        "new_death": "110",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44204"
    },
    {
        "submission_date": "1/21/2021",
        "new_case": "5049",
        "new_death": "96",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44217"
    },
    {
        "submission_date": "2/22/2021",
        "new_case": "2704",
        "new_death": "16",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44249"
    },
    {
        "submission_date": "6/20/2021",
        "new_case": "208",
        "new_death": "4",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44367"
    },
    {
        "submission_date": "2/13/2021",
        "new_case": "3757",
        "new_death": "47",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44240"
    },
    {
        "submission_date": "8/6/2021",
        "new_case": "1346",
        "new_death": "7",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44414"
    },
    {
        "submission_date": "11/29/2021",
        "new_case": "2241",
        "new_death": "9",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44529"
    },
    {
        "submission_date": "9/7/2021",
        "new_case": "354",
        "new_death": "26",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44446"
    },
    {
        "submission_date": "7/2/2021",
        "new_case": "310",
        "new_death": "5",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44379"
    },
    {
        "submission_date": "11/23/2021",
        "new_case": "2640",
        "new_death": "30",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44523"
    },
    {
        "submission_date": "4/22/2021",
        "new_case": "3230",
        "new_death": "30",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44308"
    },
    {
        "submission_date": "1/15/2021",
        "new_case": "6311",
        "new_death": "67",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44211"
    },
    {
        "submission_date": "10/30/2021",
        "new_case": "1230",
        "new_death": "11",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44499"
    },
    {
        "submission_date": "8/9/2021",
        "new_case": "861",
        "new_death": "0",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44417"
    },
    {
        "submission_date": "5/5/2021",
        "new_case": "2528",
        "new_death": "49",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44321"
    },
    {
        "submission_date": "5/31/2021",
        "new_case": "197",
        "new_death": "5",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44347"
    },
    {
        "submission_date": "10/18/2021",
        "new_case": "767",
        "new_death": "12",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44487"
    },
    {
        "submission_date": "10/28/2021",
        "new_case": "1965",
        "new_death": "20",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44497"
    },
    {
        "submission_date": "8/1/2021",
        "new_case": "928",
        "new_death": "5",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44409"
    },
    {
        "submission_date": "9/27/2021",
        "new_case": "1159",
        "new_death": "18",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44466"
    },
    {
        "submission_date": "5/9/2021",
        "new_case": "339",
        "new_death": "10",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44325"
    },
    {
        "submission_date": "11/5/2021",
        "new_case": "1385",
        "new_death": "51",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44505"
    },
    {
        "submission_date": "8/23/2021",
        "new_case": "1624",
        "new_death": "3",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44431"
    },
    {
        "submission_date": "5/15/2021",
        "new_case": "646",
        "new_death": "20",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44331"
    },
    {
        "submission_date": "8/27/2021",
        "new_case": "2592",
        "new_death": "19",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44435"
    },
    {
        "submission_date": "4/27/2021",
        "new_case": "2124",
        "new_death": "61",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44313"
    },
    {
        "submission_date": "10/31/2021",
        "new_case": "1215",
        "new_death": "0",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44500"
    },
    {
        "submission_date": "6/24/2021",
        "new_case": "272",
        "new_death": "6",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44371"
    },
    {
        "submission_date": "6/27/2021",
        "new_case": "150",
        "new_death": "3",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44374"
    },
    {
        "submission_date": "10/2/2021",
        "new_case": "1935",
        "new_death": "22",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44471"
    },
    {
        "submission_date": "8/13/2021",
        "new_case": "1844",
        "new_death": "9",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44421"
    },
    {
        "submission_date": "10/25/2021",
        "new_case": "943",
        "new_death": "12",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44494"
    },
    {
        "submission_date": "12/20/2021",
        "new_case": "7095",
        "new_death": "16",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44550"
    },
    {
        "submission_date": "2/16/2021",
        "new_case": "3633",
        "new_death": "31",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44243"
    },
    {
        "submission_date": "11/25/2021",
        "new_case": "2851",
        "new_death": "16",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44525"
    },
    {
        "submission_date": "12/4/2021",
        "new_case": "4414",
        "new_death": "18",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44534"
    },
    {
        "submission_date": "11/14/2021",
        "new_case": "1701",
        "new_death": "3",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44514"
    },
    {
        "submission_date": "7/21/2021",
        "new_case": "699",
        "new_death": "5",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44398"
    },
    {
        "submission_date": "1/9/2021",
        "new_case": "8607",
        "new_death": "98",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44205"
    },
    {
        "submission_date": "2/18/2021",
        "new_case": "3277",
        "new_death": "89",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44245"
    },
    {
        "submission_date": "2/19/2021",
        "new_case": "3047",
        "new_death": "63",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44246"
    },
    {
        "submission_date": "3/6/2021",
        "new_case": "3720",
        "new_death": "36",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44261"
    },
    {
        "submission_date": "9/23/2021",
        "new_case": "2252",
        "new_death": "24",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44462"
    },
    {
        "submission_date": "11/9/2021",
        "new_case": "1764",
        "new_death": "27",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44509"
    },
    {
        "submission_date": "9/12/2021",
        "new_case": "1847",
        "new_death": "4",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44451"
    },
    {
        "submission_date": "11/19/2021",
        "new_case": "2239",
        "new_death": "13",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44519"
    },
    {
        "submission_date": "6/14/2021",
        "new_case": "231",
        "new_death": "4",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44361"
    },
    {
        "submission_date": "5/3/2021",
        "new_case": "983",
        "new_death": "16",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44319"
    },
    {
        "submission_date": "2/11/2021",
        "new_case": "3656",
        "new_death": "79",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44238"
    },
    {
        "submission_date": "1/7/2021",
        "new_case": "7539",
        "new_death": "123",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44203"
    },
    {
        "submission_date": "4/4/2021",
        "new_case": "3799",
        "new_death": "5",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44290"
    },
    {
        "submission_date": "1/18/2021",
        "new_case": "3853",
        "new_death": "19",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44214"
    },
    {
        "submission_date": "1/3/2021",
        "new_case": "4049",
        "new_death": "21",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44199"
    },
    {
        "submission_date": "6/13/2021",
        "new_case": "207",
        "new_death": "3",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44360"
    },
    {
        "submission_date": "11/8/2021",
        "new_case": "852",
        "new_death": "7",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44508"
    },
    {
        "submission_date": "4/30/2021",
        "new_case": "1741",
        "new_death": "25",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44316"
    },
    {
        "submission_date": "11/7/2021",
        "new_case": "926",
        "new_death": "5",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44507"
    },
    {
        "submission_date": "10/19/2021",
        "new_case": "1238",
        "new_death": "31",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44488"
    },
    {
        "submission_date": "6/29/2021",
        "new_case": "222",
        "new_death": "6",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44376"
    },
    {
        "submission_date": "8/31/2021",
        "new_case": "2128",
        "new_death": "18",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44439"
    },
    {
        "submission_date": "9/19/2021",
        "new_case": "1909",
        "new_death": "8",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44458"
    },
    {
        "submission_date": "10/7/2021",
        "new_case": "2065",
        "new_death": "9",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44476"
    },
    {
        "submission_date": "8/10/2021",
        "new_case": "1629",
        "new_death": "9",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44418"
    },
    {
        "submission_date": "5/4/2021",
        "new_case": "1004",
        "new_death": "42",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44320"
    },
    {
        "submission_date": "2/3/2021",
        "new_case": "2311",
        "new_death": "109",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44230"
    },
    {
        "submission_date": "6/28/2021",
        "new_case": "148",
        "new_death": "1",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44375"
    },
    {
        "submission_date": "12/5/2021",
        "new_case": "3496",
        "new_death": "5",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44535"
    },
    {
        "submission_date": "10/29/2021",
        "new_case": "1306",
        "new_death": "12",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44498"
    },
    {
        "submission_date": "3/4/2021",
        "new_case": "3193",
        "new_death": "42",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44259"
    },
    {
        "submission_date": "1/20/2021",
        "new_case": "5438",
        "new_death": "152",
        "Year": "2021",
        "Month": "Jan",
        "state": "NJ",
        "Months": "1",
        "submission_dates": "January",
        "-Months": "44216"
    },
    {
        "submission_date": "7/31/2021",
        "new_case": "1182",
        "new_death": "7",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44408"
    },
    {
        "submission_date": "3/15/2021",
        "new_case": "2660",
        "new_death": "22",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44270"
    },
    {
        "submission_date": "8/19/2021",
        "new_case": "2022",
        "new_death": "10",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44427"
    },
    {
        "submission_date": "5/25/2021",
        "new_case": "389",
        "new_death": "24",
        "Year": "2021",
        "Month": "May",
        "state": "NJ",
        "Months": "5",
        "submission_dates": "May",
        "-Months": "44341"
    },
    {
        "submission_date": "10/13/2021",
        "new_case": "1746",
        "new_death": "29",
        "Year": "2021",
        "Month": "Oct",
        "state": "NJ",
        "Months": "10",
        "submission_dates": "October",
        "-Months": "44482"
    },
    {
        "submission_date": "11/20/2021",
        "new_case": "2199",
        "new_death": "7",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44520"
    },
    {
        "submission_date": "12/14/2021",
        "new_case": "4397",
        "new_death": "24",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44544"
    },
    {
        "submission_date": "7/10/2021",
        "new_case": "311",
        "new_death": "5",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44387"
    },
    {
        "submission_date": "8/17/2021",
        "new_case": "1821",
        "new_death": "19",
        "Year": "2021",
        "Month": "Aug",
        "state": "NJ",
        "Months": "8",
        "submission_dates": "August",
        "-Months": "44425"
    },
    {
        "submission_date": "9/16/2021",
        "new_case": "2958",
        "new_death": "26",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44455"
    },
    {
        "submission_date": "6/7/2021",
        "new_case": "208",
        "new_death": "6",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44354"
    },
    {
        "submission_date": "9/28/2021",
        "new_case": "1888",
        "new_death": "34",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44467"
    },
    {
        "submission_date": "4/7/2021",
        "new_case": "4243",
        "new_death": "49",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44293"
    },
    {
        "submission_date": "4/10/2021",
        "new_case": "3599",
        "new_death": "33",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44296"
    },
    {
        "submission_date": "11/30/2021",
        "new_case": "3251",
        "new_death": "42",
        "Year": "2021",
        "Month": "Nov",
        "state": "NJ",
        "Months": "11",
        "submission_dates": "November",
        "-Months": "44530"
    },
    {
        "submission_date": "6/16/2021",
        "new_case": "283",
        "new_death": "12",
        "Year": "2021",
        "Month": "Jun",
        "state": "NJ",
        "Months": "6",
        "submission_dates": "June",
        "-Months": "44363"
    },
    {
        "submission_date": "3/26/2021",
        "new_case": "5599",
        "new_death": "28",
        "Year": "2021",
        "Month": "Mar",
        "state": "NJ",
        "Months": "3",
        "submission_dates": "March",
        "-Months": "44281"
    },
    {
        "submission_date": "9/24/2021",
        "new_case": "2236",
        "new_death": "19",
        "Year": "2021",
        "Month": "Sep",
        "state": "NJ",
        "Months": "9",
        "submission_dates": "September",
        "-Months": "44463"
    },
    {
        "submission_date": "7/26/2021",
        "new_case": "521",
        "new_death": "4",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44403"
    },
    {
        "submission_date": "2/5/2021",
        "new_case": "4228",
        "new_death": "93",
        "Year": "2021",
        "Month": "Feb",
        "state": "NJ",
        "Months": "2",
        "submission_dates": "February",
        "-Months": "44232"
    },
    {
        "submission_date": "7/29/2021",
        "new_case": "1077",
        "new_death": "1",
        "Year": "2021",
        "Month": "Jul",
        "state": "NJ",
        "Months": "7",
        "submission_dates": "July",
        "-Months": "44406"
    },
    {
        "submission_date": "4/23/2021",
        "new_case": "2834",
        "new_death": "27",
        "Year": "2021",
        "Month": "Apr",
        "state": "NJ",
        "Months": "4",
        "submission_dates": "April",
        "-Months": "44309"
    },
    {
        "submission_date": "12/31/2021",
        "new_case": "33724",
        "new_death": "37",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44561"
    },
    {
        "submission_date": "12/26/2021",
        "new_case": "14159",
        "new_death": "7",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44556"
    },
    {
        "submission_date": "12/21/2021",
        "new_case": "8494",
        "new_death": "32",
        "Year": "2021",
        "Month": "Dec",
        "state": "NJ",
        "Months": "12",
        "submission_dates": "December",
        "-Months": "44551"
    }
]
'''

# Load the JSON data
data = json.loads(json_data)

# Modify the values
for entry in data:
    entry['new_case'] = int(entry['new_case'])
    entry['new_death'] = int(entry['new_death'])
    entry['Year'] = int(entry['Year'])
    entry['Months'] = int(entry['Months'])

# Save the modified data to a new JSON file
output_file = 'nj_data.json'
with open(output_file, 'w') as f:
    json.dump(data, f, indent=4)

print(f"The modified JSON data has been saved to {output_file}.")
